---
- hosts: all
  become: true
  tasks:
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    when: ansible_facts['os_family'] == "Debian"

  - name: Install packages that allow yum to be used over HTTPS
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - curl
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    when: ansible_facts['os_family'] == "RedHat"
 
  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo
    become: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status
    when: ansible_facts['os_family'] == "Debian"

  - name: Install docker and its dependecies
    yum: 
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status
    when: ansible_facts['os_family'] == "RedHat"

  handlers:
    - name: docker status
      service: name=docker state=started
